#!/usr/bin/env node
// Depth lint — measures which skills have reached the flagship craft bar
// (docs/AUTHORING-DEPTH.md) and which are still template-shaped. It does NOT
// gate CI; it produces a ranked worklist so the library can be upgraded
// deliberately instead of by vibes.
//
//   node scripts/depth-lint.mjs                 # summary + top upgrade candidates
//   node scripts/depth-lint.mjs --report        # also write docs/craft/DEPTH-REPORT.md
//   node scripts/depth-lint.mjs --json          # machine-readable
//
// Signals (heuristic, honest about it):
//   loop        — has phased process w/ completion criteria ("Done when:")
//   compose     — invokes a neighbor skill (/skill-name) or names a spine
//   disclose    — pushes reference into references/ (progressive disclosure)
//   A skill scores 0–3. 3 = flagship-shaped; 0–1 = template-shaped.
import { readdirSync, readFileSync, existsSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const skillsDir = join(root, 'skills');
const arg = (n) => process.argv.includes(`--${n}`);

const names = readdirSync(skillsDir).filter((n) => existsSync(join(skillsDir, n, 'SKILL.md')));

const rows = names.map((name) => {
  const body = readFileSync(join(skillsDir, name, 'SKILL.md'), 'utf8');
  const loop = /done when:/i.test(body);
  // composition: an explicit /skill-name invocation, or a stated spine/handoff
  const compose = /\/[a-z][a-z0-9-]{2,}\b/.test(body.replace(/https?:\/\//g, '')) &&
    /(spine|hand(s| )off|→\s*\/|invoke|upstream|downstream|receives .* from|hands .* to)/i.test(body);
  const disclose = existsSync(join(skillsDir, name, 'references')) &&
    readdirSync(join(skillsDir, name, 'references')).some((f) => f.endsWith('.md')) &&
    /references\/[a-z0-9-]+\.md/i.test(body); // referenced, not just present
  const score = [loop, compose, disclose].filter(Boolean).length;
  return { name, loop, compose, disclose, score, lines: body.split('\n').length };
});

const total = rows.length;
const at = (s) => rows.filter((r) => r.score === s).length;
const withLoop = rows.filter((r) => r.loop).length;
const withCompose = rows.filter((r) => r.compose).length;
const flagship = rows.filter((r) => r.score === 3);

if (arg('json')) { console.log(JSON.stringify({ total, rows }, null, 2)); process.exit(0); }

console.log(`Depth lint — ${total} skills against the flagship bar (docs/AUTHORING-DEPTH.md)\n`);
console.log(`  loop (completion criteria):   ${withLoop} (${(100 * withLoop / total).toFixed(1)}%)`);
console.log(`  compose (invokes a neighbor): ${withCompose} (${(100 * withCompose / total).toFixed(1)}%)`);
console.log(`  score 3 (flagship-shaped):    ${at(3)}`);
console.log(`  score 2:                      ${at(2)}`);
console.log(`  score 0-1 (template-shaped):  ${at(0) + at(1)}\n`);
console.log('Flagship-shaped so far:');
for (const r of flagship.sort((a, b) => a.name.localeCompare(b.name))) console.log(`  ✓ ${r.name}`);

// Best upgrade candidates: the most-used-looking (short, foundational) template skills.
// Heuristic proxy for "high value": no loop yet, and a substantial body already.
const candidates = rows.filter((r) => !r.loop).sort((a, b) => b.lines - a.lines).slice(0, 25);
console.log('\nTop 25 upgrade candidates (substantial skills still missing a process loop):');
for (const r of candidates) console.log(`  ${r.score}/3  ${r.name}  (${r.lines} lines)`);

if (arg('report')) {
  const md = [
    '# Depth report — the flagship-craft worklist',
    '',
    `Generated by \`scripts/depth-lint.mjs\` against [docs/AUTHORING-DEPTH.md](../AUTHORING-DEPTH.md). Heuristic, not a gate — a worklist for turning template skills into processes.`,
    '',
    `- **${total}** skills total`,
    `- **${withLoop}** have completion criteria (\`Done when:\`) — ${(100 * withLoop / total).toFixed(1)}%`,
    `- **${withCompose}** invoke a neighbor skill`,
    `- **${at(3)}** are flagship-shaped (loop + compose + disclose)`,
    '',
    '## Flagship-shaped',
    flagship.length ? flagship.map((r) => `- ${r.name}`).join('\n') : '_(none yet)_',
    '',
    '## Top upgrade candidates',
    'Substantial skills still missing a process loop — the highest-value targets for the next depth pass.',
    '',
    '| Skill | Score | Lines | Has loop | Composes | Discloses |',
    '|---|---|---|---|---|---|',
    ...candidates.map((r) => `| ${r.name} | ${r.score}/3 | ${r.lines} | ${r.loop ? '✓' : '—'} | ${r.compose ? '✓' : '—'} | ${r.disclose ? '✓' : '—'} |`),
    '',
  ].join('\n');
  writeFileSync(join(root, 'docs', 'craft', 'DEPTH-REPORT.md'), md + '\n');
  console.log('\nWrote docs/craft/DEPTH-REPORT.md');
}
